######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 27 10:48:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += yaojang.h
FORMS += yaojang.ui
SOURCES += main.cpp yaojang.cpp
RESOURCES += pics.qrc
