######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 27 10:35:33 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snakegame.h
SOURCES += main.cpp snakegame.cpp
