######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 26 19:10:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Cell.h MineGame.h
SOURCES += MineGame.cpp test.cpp
RESOURCES += pics.qrc
