######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 15 19:46:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first.cpp
